"""GTFS Realtime routes alias under /realtime/.

Reuses the existing ViewSets and APIViews from `api.views`. Each
registration declares an explicit `basename=` / `name=` prefixed with
`realtime-` to avoid clashing with the URL names generated by the legacy
`/api/` router.
"""

from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(
    r"feed-messages",
    views.FeedMessageViewSet,
    basename="realtime-feed-message",
)
router.register(
    r"trip-updates",
    views.TripUpdateViewSet,
    basename="realtime-trip-update",
)
router.register(
    r"stop-time-updates",
    views.StopTimeUpdateViewSet,
    basename="realtime-stop-time-update",
)
router.register(
    r"vehicle-positions",
    views.VehiclePositionViewSet,
    basename="realtime-vehicle-position",
)
router.register(
    r"service-alerts",
    views.ServiceAlertViewSet,
    basename="realtime-service-alert",
)

urlpatterns = [
    path("", include(router.urls)),
    path("next-trips/", views.NextTripView.as_view(), name="realtime-next-trips"),
    path("next-stops/", views.NextStopView.as_view(), name="realtime-next-stops"),
    path("route-stops/", views.RouteStopView.as_view(), name="realtime-route-stops"),
]
