"""GTFS Schedule routes alias under /schedule/.

Reuses the existing ViewSets from `api.views`. Each registration declares
an explicit `basename=` prefixed with `schedule-` to avoid clashing with
the URL names generated by the legacy `/api/` router.
"""

from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r"agencies", views.AgencyViewSet, basename="schedule-agency")
router.register(r"stops", views.StopViewSet, basename="schedule-stop")
router.register(r"geo-stops", views.GeoStopViewSet, basename="schedule-geo-stop")
router.register(r"shapes", views.ShapeViewSet, basename="schedule-shape")
router.register(r"geo-shapes", views.GeoShapeViewSet, basename="schedule-geo-shape")
router.register(r"routes", views.RouteViewSet, basename="schedule-route")
router.register(r"calendars", views.CalendarViewSet, basename="schedule-calendar")
router.register(
    r"calendar-dates",
    views.CalendarDateViewSet,
    basename="schedule-calendar-date",
)
router.register(r"trips", views.TripViewSet, basename="schedule-trip")
router.register(r"stop-times", views.StopTimeViewSet, basename="schedule-stop-time")
router.register(
    r"fare-attributes",
    views.FareAttributeViewSet,
    basename="schedule-fare-attribute",
)
router.register(r"fare-rules", views.FareRuleViewSet, basename="schedule-fare-rule")
router.register(r"feed-info", views.FeedInfoViewSet, basename="schedule-feed-info")

urlpatterns = [
    path("", include(router.urls)),
]
