# Generated by Django 5.2.6 on 2026-01-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('report_type', models.CharField(max_length=255)),
                ('location_stop_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('user_evidence', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('reviewed', 'reviewed'), ('resolved', 'resolved')], default='pending', max_length=16)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WideAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_id', models.CharField(max_length=255, unique=True)),
                ('alert_header', models.CharField(max_length=255)),
                ('alert_description', models.TextField()),
                ('alert_url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
